---
collections:
  - name: ansible.posix
  - name: community.general
  - name: infra.controller_configuration
  - name: infra.ah_configuration
  - name: infra.ee_utilities
  - name: infra.aap_utilities
  - name: containers.podman
  - name: awx.awx
...
